name: Run Cucumber Java Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-automation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Run Cucumber tests
#        run: mvn test -Dcucumber.options="--plugin pretty --plugin html:target/cucumber-reports.html"
#
#      - name: Upload Cucumber report
#        uses: actions/upload-artifact@v2
#        with:
#          name: cucumber-report